### ISSUE TITLE
Which .cfg you use？

### ISSUE THREAD

**Issue by wuqi930907** [gudovskiy/yoloNCS#12]
Hi ,

I want to convert my cfg file to prototxt format.
I use one of this dir's file(http://github.com/pjreddie/darknet/cfg/yolov1).,
then I use xingwangsfu's tools(https://github.com/xingwangsfu/caffe-yolo),but the result is not good.
Can you tell me which cfg you used?

Thanks

**Comment by gudovskiy** [comment]
@wuqi930907, try to look at older revisions of darknet repo. Some of older YOLOv1 was replaced by v2 cfgs. I posted somewhere revision number I used.

**Comment by wuqi930907** [comment]
Thank you very much for your help @gudovskiy

**Comment by wuqi930907** [comment]
I can't find any older visions of darknet.
May you help me get those cfgs that can be converted to caffe'prototxt format correctly?
Can you upload those cfgs you used or give me the suitable vision of darknet's link?
Thank you very much ！ @gudovskiy

**Comment by wuqi930907** [comment]
I have sloved this problem,thanks again!  @gudovskiy
