### ISSUE TITLE
Example typo/error

### ISSUE THREAD

**Issue by apiszcz** [gudovskiy/yoloNCS#3]
mvNCCompile prototxt/yolo_tiny_deploy.prototxt -w weights/yolo_tiny**_deploy**.caffemodel -s 12

EIther one needs to change the name of the weight file or use this name for downloaded weight file.

mvNCCompile prototxt/yolo_tiny_deploy.prototxt -w weights/yolo_tiny.caffemodel -s 12

**Comment by gudovskiy** [comment]
@apiszcz true.
